[package]
name = "curbot"
version = "0.1.0"
edition = "2024"

[dependencies]
humantime-serde = "1.1.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sysinfo = "0.37.2"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }

[workspace]